site_name: ONE documentation
site_url: https://docs.expl.one/
site_description: Official documentation for the ONE ecosystem. Decentralized infrastructure powered by EXPL Nodes. 45% revenue to EXPL Nodes, 45% to ONE Creators, 10% to founders.
site_author: EXPL.ONE Team
repo_url: https://github.com/explorills/docs
repo_name: explorills/docs

# SEO and Analytics
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - toc.follow

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

extra:
  analytics:
    provider: google
    property: G-3NM3XM3TX2
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/explorills
      name: EXPL.ONE on GitHub
    - icon: fontawesome/brands/twitter
      link: https://x.com/explorills_main
      name: EXPL.ONE on Twitter
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/RetTCVq7tJ
      name: EXPL.ONE Discord
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/explorills
      name: EXPL.ONE on LinkedIn

copyright: Copyright &copy; 2026 EXPL.ONE. All Rights Reserved.

nav:
  - Home: index.md
  - 2026 Roadmap: roadmap-2026.md
  - EXPL Nodes:
      - Introduction: nodes/introduction.md
      - EXPL Nodes Overview: nodes/node-nft-licenses.md
      - Node Escrow: nodes/node-escrow.md
      - Node Pricing Structure: nodes/node-pricing-structure.md
      - How to Purchase: nodes/how-to-purchase-node.md
  - ONE Projects:
      - ONE pump: one-pump/introduction.md
      - ONE network: one-network/introduction.md
      - ONE world: one-world/introduction.md
      - Projects Overview: projects/overview.md
  - Tokenomics:
      - Tokenomics Introduction: tokenomics/introduction.md
      - General Overview: tokenomics/general-overview.md
      - Supply & Allocation: tokenomics/supply.md
  - Distribution Framework:
      - Distribution Master Map: distribution-framework/introduction.md
      - Node-Based Distribution: distribution-framework/node-based-distribution.md
      - Direct Mint Channels: distribution-framework/direct-mint-channels.md
  - Get Involved:
      - Contribute: get-involved/contribute.md
      - Collaborations: get-involved/collabs.md
      - Venture Opportunities: get-involved/venture-opportunities.md
  - Additional Information:
      - Under Development: additional-information/under-development.md
      - Official Links: additional-information/official-links.md
  - Archive:
      - Archive Overview: archive/overview.md
      - TNO Cards:
          - TNO Introduction: archive/tno-cards/introduction.md
          - TNO Contract: archive/tno-cards/tno-contract.md
          - TNO Cards Pricing: archive/tno-cards/tno-cards-pricing.md
          - How to Mint TNO Cards: archive/tno-cards/how-to-mint-tno-cards.md


